#! /bin/sh

# webdav-file-sync
# Copyright (c) 2023 Johannes Lehtinen

# Check if username or password was requested
case "$1" in

    # Username requested
    Username*)
        echo "$SYNC_REMOTE_USER"
        ;;

    # Password requested
    Password*)
        echo "$SYNC_REMOTE_PASSWORD"
        ;;

esac
